/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_dip_firstnote_objecttrackingtest_MedianTracker */

#ifndef _Included_jp_dip_firstnote_objecttrackingtest_MedianTracker
#define _Included_jp_dip_firstnote_objecttrackingtest_MedianTracker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_dip_firstnote_objecttrackingtest_MedianTracker
 * Method:    nativeInit
 * Signature: (JLorg/opencv/core/Rect;)V
 */
JNIEXPORT void JNICALL Java_jp_dip_firstnote_objecttrackingtest_MedianTracker_nativeInit
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     jp_dip_firstnote_objecttrackingtest_MedianTracker
 * Method:    nativeRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jp_dip_firstnote_objecttrackingtest_MedianTracker_nativeRelease
  (JNIEnv *, jobject);

/*
 * Class:     jp_dip_firstnote_objecttrackingtest_MedianTracker
 * Method:    nativeUpdate
 * Signature: (JLorg/opencv/core/Rect;)V
 */
JNIEXPORT void JNICALL Java_jp_dip_firstnote_objecttrackingtest_MedianTracker_nativeUpdate
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
